// Mock data cho My Challenge feature
import { TrainingPlanDetail, UserCurrentTrainingPlan } from '../types/myChallenge.type';

export const mockUserCurrentTrainingPlans: UserCurrentTrainingPlan[] = [
  {
    id: 1,
    trainingPlanId: 1,
    planName: '30-Day Push-up Master',
    description: 'Build strength and endurance with progressive push-up training',
    difficulty: 'Intermediate',
    duration: '30 days',
    progressPercentage: 40,
    startDate: '2025-11-04',
    endDate: '2025-12-04',
    daysCompleted: 12,
    totalDays: 30,
    lastActivityDate: '2025-11-15',
  },
  {
    id: 2,
    trainingPlanId: 2,
    planName: 'AI Running Speed Program',
    description: 'Improve your 5K time with AI-coached running intervals',
    difficulty: 'Advanced',
    duration: '8 weeks',
    progressPercentage: 25,
    startDate: '2025-11-01',
    endDate: '2025-12-20',
    daysCompleted: 14,
    totalDays: 56,
    lastActivityDate: '2025-11-15',
  },
  {
    id: 3,
    trainingPlanId: 3,
    planName: 'Core Strength Foundation',
    description: 'Build a solid core foundation with daily exercises',
    difficulty: 'Beginner',
    duration: '21 days',
    progressPercentage: 62,
    startDate: '2025-10-25',
    endDate: '2025-11-15',
    daysCompleted: 13,
    totalDays: 21,
    lastActivityDate: '2025-11-15',
  },
];

export const mockTrainingPlanDetail: TrainingPlanDetail = {
  id: '1',
  planName: '30-Day Push-up Master',
  description: 'Build strength and endurance with progressive push-up training',
  duration: '30 days',
  startDate: '2025-11-04',
  endDate: '2025-12-04',
  difficulty: 'Intermediate',
  totalDays: 30,
  progressPercentage: 40,
  status: 'active',
  userId: 'current-user',
  dayChallenges: [
    {
      dayNumber: 1,
      dayName: 'Day 1 - Monday',
      challenges: [
        {
          id: 1,
          challengeId: 1,
          challengeName: 'Basic Push-ups',
          title: 'Basic Push-ups',
          sets: 3,
          reps: 10,
          status: 'COMPLETED',
          description: 'Standard push-ups with proper form',
          difficulty: 'EASY',
          videoUrl: 'uploads/videos/pushups_basic.mov',
          aiAnalysis: {
            correctReps: 30,
            totalReps: 30,
            accuracy: 95,
            feedback: 'Excellent form! Keep your back straight.',
            posture: 'Correct',
          },
        },
        {
          id: 2,
          challengeId: 2,
          challengeName: 'Diamond Push-ups',
          title: 'Diamond Push-ups',
          sets: 2,
          reps: 8,
          status: 'ACTIVE',
          description: 'Advanced push-up variation',
          difficulty: 'MEDIUM',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 2,
      dayName: 'Day 2 - Tuesday',
      challenges: [
        {
          id: 3,
          challengeId: 3,
          challengeName: 'Wide Grip Push-ups',
          title: 'Wide Grip Push-ups',
          sets: 3,
          reps: 12,
          status: 'INACTIVE',
          description: 'Push-ups with wider hand placement',
          difficulty: 'MEDIUM',
          videoUrl: '',
        },
        {
          id: 4,
          challengeId: 4,
          challengeName: 'Push-up Holds',
          title: 'Push-up Holds',
          sets: 2,
          reps: 5,
          status: 'INACTIVE',
          description: 'Hold at bottom position for 3 seconds',
          difficulty: 'HARD',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 3,
      dayName: 'Day 3 - Wednesday',
      challenges: [
        {
          id: 5,
          challengeId: 5,
          challengeName: 'Decline Push-ups',
          title: 'Decline Push-ups',
          sets: 3,
          reps: 10,
          status: 'INACTIVE',
          description: 'Feet elevated push-ups',
          difficulty: 'HARD',
          videoUrl: '',
        },
        {
          id: 6,
          challengeId: 6,
          challengeName: 'Plank to Push-up',
          title: 'Plank to Push-up',
          sets: 2,
          reps: 8,
          status: 'INACTIVE',
          description: 'From plank position to full push-up',
          difficulty: 'HARD',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 4,
      dayName: 'Day 4 - Thursday',
      challenges: [
        {
          id: 7,
          challengeId: 7,
          challengeName: 'Explosive Push-ups',
          title: 'Explosive Push-ups',
          sets: 3,
          reps: 8,
          status: 'INACTIVE',
          description: 'Push-ups with hand clap',
          difficulty: 'HARD',
          videoUrl: '',
        },
        {
          id: 8,
          challengeId: 8,
          challengeName: 'Single Arm Push-ups (Assist)',
          title: 'Single Arm Push-ups (Assist)',
          sets: 2,
          reps: 5,
          status: 'INACTIVE',
          description: 'Single arm with assistance',
          difficulty: 'HARD',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 5,
      dayName: 'Day 5 - Friday',
      challenges: [
        {
          id: 9,
          challengeId: 9,
          challengeName: 'Rest and Recovery',
          title: 'Rest and Recovery',
          sets: 1,
          reps: 1,
          status: 'INACTIVE',
          description: 'Light stretching and recovery exercises',
          difficulty: 'EASY',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 6,
      dayName: 'Day 6 - Saturday',
      challenges: [
        {
          id: 10,
          challengeId: 10,
          challengeName: 'Full Body Push-up Test',
          title: 'Full Body Push-up Test',
          sets: 5,
          reps: 15,
          status: 'INACTIVE',
          description: 'Maximum reps in 5 sets',
          difficulty: 'HARD',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 7,
      dayName: 'Day 7 - Sunday',
      challenges: [
        {
          id: 11,
          challengeId: 11,
          challengeName: 'Active Rest',
          title: 'Active Rest',
          sets: 1,
          reps: 1,
          status: 'INACTIVE',
          description: 'Light walk or yoga',
          difficulty: 'EASY',
          videoUrl: '',
        },
      ],
    },
  ],
};

export const mockTrainingPlanDetailWeek2: TrainingPlanDetail = {
  ...mockTrainingPlanDetail,
  dayChallenges: [
    {
      dayNumber: 8,
      dayName: 'Day 8 - Monday',
      challenges: [
        {
          id: 12,
          challengeId: 12,
          challengeName: 'Standard Push-ups',
          title: 'Standard Push-ups',
          sets: 4,
          reps: 12,
          status: 'COMPLETED',
          description: 'Standard push-ups progression',
          difficulty: 'MEDIUM',
          videoUrl: 'uploads/videos/pushups_standard.mov',
          aiAnalysis: {
            correctReps: 48,
            totalReps: 48,
            accuracy: 92,
            feedback: 'Good form, slightly lower on some reps.',
            posture: 'Good',
          },
        },
      ],
    },
    {
      dayNumber: 9,
      dayName: 'Day 9 - Tuesday',
      challenges: [
        {
          id: 13,
          challengeId: 13,
          challengeName: 'Diamond Push-ups',
          title: 'Diamond Push-ups',
          sets: 3,
          reps: 10,
          status: 'INACTIVE',
          description: 'Diamond push-ups progression',
          difficulty: 'MEDIUM',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 10,
      dayName: 'Day 10 - Wednesday',
      challenges: [
        {
          id: 14,
          challengeId: 14,
          challengeName: 'Decline Push-ups',
          title: 'Decline Push-ups',
          sets: 4,
          reps: 12,
          status: 'INACTIVE',
          description: 'Decline push-ups progression',
          difficulty: 'HARD',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 11,
      dayName: 'Day 11 - Thursday',
      challenges: [
        {
          id: 15,
          challengeId: 15,
          challengeName: 'Explosive Push-ups',
          title: 'Explosive Push-ups',
          sets: 3,
          reps: 10,
          status: 'INACTIVE',
          description: 'Explosive push-ups progression',
          difficulty: 'HARD',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 12,
      dayName: 'Day 12 - Friday',
      challenges: [
        {
          id: 16,
          challengeId: 16,
          challengeName: 'Archer Push-ups',
          title: 'Archer Push-ups',
          sets: 3,
          reps: 8,
          status: 'INACTIVE',
          description: 'Archer push-ups progression',
          difficulty: 'HARD',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 13,
      dayName: 'Day 13 - Saturday',
      challenges: [
        {
          id: 17,
          challengeId: 17,
          challengeName: 'Max Reps Test',
          title: 'Max Reps Test',
          sets: 5,
          reps: 20,
          status: 'INACTIVE',
          description: 'Maximum reps test',
          difficulty: 'HARD',
          videoUrl: '',
        },
      ],
    },
    {
      dayNumber: 14,
      dayName: 'Day 14 - Sunday',
      challenges: [
        {
          id: 18,
          challengeId: 18,
          challengeName: 'Recovery Day',
          title: 'Recovery Day',
          sets: 1,
          reps: 1,
          status: 'INACTIVE',
          description: 'Recovery day light activities',
          difficulty: 'EASY',
          videoUrl: '',
        },
      ],
    },
  ],
};
